services:
  db:
    image: postgres:16-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=auth_db
    volumes:
      - data-postgres:/var/lib/postgresql/data
volumes:
  data-postgres: