db:
  username: ${DB_USERNAME:postgres}
  password: ${DB_PASSWORD:secret}
  url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/${DB_NAME:auth_db}

security:
  jwt:
    expiration-in-minutes: ${EXPIRATION_IN_MINUTES:30}
    secret-key: ${SECRET_KEY:Zmxha3NkZmw7YXNmajtzbGFmamFsc2Rmajthc2xmajthc2Rm}
